In [9]:
import numpy as np
from numpy import array
import pandas as pd
import csv


In [2]:
PATH = 'hdfs_train.csv'
with open(PATH, newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
for i in range(len(data)):
    while('' in data[i]):
        data[i].remove('')

In [10]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

trial = data[0]
res = [eval(i) for i in trial]
t = [int(i) for i in res]
t.pop(0)

# choose a number of time steps
n_steps = 5
# split into samples
X, y = split_sequence(t, n_steps)
# summarize the data
tot = [X,y]
for i in range(len(X)):
    print(X[i], y[i])

[ 5  5  5 22 11] 9
[ 5  5 22 11  9] 11
[ 5 22 11  9 11] 9
[22 11  9 11  9] 11
[11  9 11  9 11] 9
[ 9 11  9 11  9] 26
[11  9 11  9 26] 26
[ 9 11  9 26 26] 26
[11  9 26 26 26] 23
[ 9 26 26 26 23] 23
[26 26 26 23 23] 23
[26 26 23 23 23] 21
[26 23 23 23 21] 21
[23 23 23 21 21] 21


In [11]:
X ,Y = list(), list()
for j in range(len(data)):
    temp = data[j]
    res = [eval(i) for i in temp]
    t = [int(i) for i in res]
    t.pop(0)
    # choose a number of time steps
    n_steps = 5
    # split into samples
    x, y = split_sequence(t, n_steps)
    # summarize the data
    for i in range(len(x)):
        X.insert(i,x[i])
        Y.insert(i,y[i])
X = array(X)
Y = array(Y)
print(len(X))

42952


[0 5 5] 5
[5 5 5] 22
[ 5  5 22] 11
[ 5 22 11] 9
[22 11  9] 11
[11  9 11] 9
[ 9 11  9] 11
[11  9 11] 9
[ 9 11  9] 26
[11  9 26] 26
[ 9 26 26] 26
[26 26 26] 23
[26 26 23] 23
[26 23 23] 23
[23 23 23] 21
[23 23 21] 21
[23 21 21] 21
[ 1 22  5] 5
[22  5  5] 5
[5 5 5] 11
[ 5  5 11] 9
[ 5 11  9] 11
[11  9 11] 9
[ 9 11  9] 11
[11  9 11] 9
[ 9 11  9] 26
[11  9 26] 26
[ 9 26 26] 26
[ 2 22  5] 5
[22  5  5] 5
[5 5 5] 11
[ 5  5 11] 9
[ 5 11  9] 11
[11  9 11] 9
[ 9 11  9] 11
[11  9 11] 9
[ 9 11  9] 26
[11  9 26] 26
[ 9 26 26] 26
[ 3  5 22] 5
[ 5 22  5] 5
[22  5  5] 26
[ 5  5 26] 26
[ 5 26 26] 11
[26 26 11] 9
[26 11  9] 11
[11  9 11] 9
[ 9 11  9] 11
[11  9 11] 9
[ 9 11  9] 26
[11  9 26] 23
[ 9 26 23] 23
[26 23 23] 23
[23 23 23] 21
[23 23 21] 21
[23 21 21] 21
[ 4  5 22] 5
[ 5 22  5] 5
[22  5  5] 11
[ 5  5 11] 9
[ 5 11  9] 11
[11  9 11] 9
[ 9 11  9] 11
[11  9 11] 9
[ 9 11  9] 26
[11  9 26] 26
[ 9 26 26] 26
[26 26 26] 23
[26 26 23] 23
[26 23 23] 23
[23 23 23] 21
[23 23 21] 21
[23 21 21] 21
[5 5 5] 5
[5 5

/tmp/ipykernel_106106/3196061956.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  dataset = np.array(data)


TypeError: list indices must be integers or slices, not tuple

In [45]:
# multi-step data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps_in, n_steps_out):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + n_steps_out
		# check if we are beyond the sequence
		if out_end_ix > len(sequence):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps


In [46]:
n_steps_in, n_steps_out = 3, 1
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] [40]
[20 30 40] [50]
[30 40 50] [60]
[40 50 60] [70]
[50 60 70] [80]
[60 70 80] [90]


[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
